name: Fast test on Ubuntu x64

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build $BUILD_TYPE/Fast=$BUILD_FAST/$BASH_PLATFORM/$CC
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - env: 
            BUILD_TYPE: MemSan
            BUILD_FAST: ON
            BASH_PLATFORM: BASH_AVX2
            CC: gcc
    steps:
    - name: Get source
      uses: actions/checkout@v3
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FAST=${{env.BUILD_FAST}} -DBASH_PLATFORM=${{env.BASH_PLATFORM}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
