name: Test on Ubuntu x64

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  BUILD_FAST: ON  
  BASH_PLATFORM: BASH_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get source
      uses: actions/checkout@v3
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FAST=${{env.BUILD_FAST}} -DBASH_PLATFORM=${{env.BASH_PLATFORM}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose

    - name: Prepare lcov
      run: sudo apt-get install -y lcov

    - name: Generate base coverage report
      run: lcov -c -i -d src -o coverage_base.info

    - name: Copy test.sh
      working-directory: 
      run: cp cmd/test/test.sh ${{github.workspace}}/build/cmd 

    - name: Run test
      working-directory: ${{github.workspace}}/build
      run: |
        test/testbee2

    - name: Run bee2cmd test
      working-directory: ${{github.workspace}}/build/cmd
      run: ./test.sh 

    - name: Generate coverage report
      run: |
        lcov -c -d src -o coverage_test.info
        lcov -a coverage_base.info -a coverage_test.info -o coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info

    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: coverage.info

